apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-demo 
  namespace: argocd
spec:
  project: k8s-project
  source:
    repoURL: https://github.com/Shakhovichkirill/microservice-project-otus.git
    targetRevision: HEAD
    path:     microservices-demo/release/
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    syncOptions:
    - CreateNamespace=true